
const getIcon = (desc) => {
    switch (desc) {
        case "thunderstorm":
            return "wi-owm-200"
        case "lightning":
            return "wi-owm-210"
        case "sprinkle":
            return "wi-owm-300"
        case "rain":
            return "wi-owm-302"
        case "rain-mix":
            return "wi-owm-511"
        case 'showers':
            return "wi-owm-521"
        case "storm-showers":
            return "wi-owm-531"
        case "snow":
            return "wi-owm-600"
        case "sleet":
            return "wi-owm-602"
        case "smoke":
            return "wi-owm-711"
        case "day-haze":
            return "wi-owm-721"
        case "dust":
            return "wi-owm-731"
        case "cloudy-gusts":
            return "wi-owm-771"
        case "tornado":
            return "wi-owm-781"
        case "day-sunny":
            return "wi-owm-800"
        case "cloudy":
            return "wi-owm-804"
        case "hurricane":
            return "wi-owm-902"
        case "snowflake-cold":
            return "wi-owm-903"
        case "hot":
            return "wi-owm-904"
        case "windy":
            return "wi-owm-905"
        case "hail":
            return "wi-owm-906"
        case "strong-wind":
            return "wi-owm-957"
        case "day-thunderstorm":
            return "wi-owm-200"
        case "day-lightning":
            return "wi-owm-211"
        case "day-sprinkle":
            return "wi-owm-300"
        case "day-rain":
            return "wi-owm-312"
        case "day-rain-mix":
            return "wi-owm-511"
        case "day-snow":
            return "wi-owm-600"
        case "day-showers":
            return "wi-owm-701"
        case "day-fog":
            return "wi-owm-741"
        case "day-sunny":
            return "wi-owm-531"
        case "day-storm-showers":
            return "wi-owm-531"
        case "night-alt-lightning":
            return "wi-owm-531"
        case "night-fog":
            return "wi-owm-741"
        case "night-clear":
            return "wi-owm-800"
        case "night-alt-cloudy":
            return "wi-owm-804"
        case "night-alt-hail":
            return "wi-owm-906"
        case "night-alt-thunderstorm":
            return "wi-owm-230"
        case "night-alt-sprinkle":
            return "wi-owm-300"
        case "night-alt-rain":
            return "wi-owm-302"
        case "night-alt-showers":
            return "wi-owm-522"
        case "night-alt-snow":
            return "wi-owm-600"
        case "night-alt-sleet":
            return "wi-owm-601"
        case" night-alt-rain-mix":
            return "wi-owm-616"
        default:
            return "false"
    }    
}

export default getIcon;